name:                puz2
version:             0.1.0.0
github:              "dbalseiro/puz2"
license:             BSD3
author:              "Diego Balseiro"
maintainer:          "dbalseiro@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dbalseiro/puz2#readme>

dependencies:
- base >= 4.7 && < 5
- mtl


ghc-options:
- -Wall
- -Werror
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates

library:
  source-dirs: src
  dependencies:
    - array

executables:
  puz2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - puz2
    - split

tests:
  puz2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - puz2
